site_name: JPHACKS2017 参加者向けガイドライン
pages:
  - ホーム:
      - '開催概要': 'index.md'
      - '審査基準': 'criteria.md'
  - 参考資料:
      - 'Git/GitHubの使い方': 'how-to-use-git-github.md'
  - 参加規約:
      - '参加規約': 'terms.md'
      - 'アンチハラスメントポリシー': 'anti-harassment.md'
theme: yeti
